old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
#    producers:
#        # use 'old_sound_rabbit_mq.task_producer' service to send data.
#        task:
#            connection:       default
#            exchange_options: { name: 'task', type: direct }
    consumers:
        news:
            connection:       default
            exchange_options: { name: 'news', type: direct }
            queue_options:    { name: 'news'}
            callback:         App\Consumer\NewsConsumer
